{
 "title": "Elektřina",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Okamžitá spotřeba elektrické energie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"Kalužovi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] =~ /Spotřeba.*/ and r[\"_measurement\"] !~ /Spotřeba vody.*/))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  \n"
    }
   ]
  },
  {
   "title": "Nabití baterie",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kalužovi\")\n  |> range(start: -1d, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] == \"Baterie\"))\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Nabití baterie",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (r[\"_measurement\"] == \"Baterie\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))  \n"
    }
   ]
  },
  {
   "title": "Denní spotřeba",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Měřič.*/ and r[\"_measurement\"] != \"Měřič Grid\" and r[\"_measurement\"] != \"Měřič FVE\" and r[\"_measurement\"] != \"Měřič Dům\" and r[\"_measurement\"] != \"Měřič baterie\" and r[\"_measurement\"] != \"Měřič vody\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  \n"
    },
    {
     "query": "import \"timezone\"\nimport \"regexp\"\nimport \"join\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nspotrebice = from(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Měřič.*/ and r[\"_measurement\"] != \"Měřič Grid\" and r[\"_measurement\"] != \"Měřič FVE\" and r[\"_measurement\"] != \"Měřič Dům\" and r[\"_measurement\"] != \"Měřič výbíjení baterie\" and r[\"_measurement\"] != \"Měřič nabíjení baterie\" and r[\"_measurement\"] != \"Měřič baterie\"  and r[\"_measurement\"] != \"Měřič vody\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum()\n\nostatni = from(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Měřič Dům\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n\n//spotrebice\njoin.time(method: \"left\", left: spotrebice, right: ostatni, as: (l, r) => ({l with _value: r._value - l._value}))\n  |> group()"
    }
   ]
  },
  {
   "title": "Denní zdroje energie",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Měřič FVE\" or r[\"_measurement\"] == \"Měřič Grid\" or r[\"_measurement\"] == \"Měřič baterie\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  "
    }
   ]
  },
  {
   "title": "Vypočtená spotřeba elektrické energie za minulých 30 dní",
   "type": "timeseries",
   "description": "Vypočteno z pravidelného hlášení měřičů. Tento údaj je tak přesný jak přesná jsou hlášení měřičů.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => (r[\"_measurement\"] =~ /Spotřeba.*/ and r[\"_measurement\"] !~ /Spotřeba vody.*/))\n  |> aggregateWindow(\n    every: 1h,\n    fn: (tables=<-, column) =>\n      tables\n        |> integral(unit: 1h)\n        |> map(fn: (r) => ({ r with _value: r._value})))\n  |> aggregateWindow(fn: sum, every: 1d)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  \n"
    }
   ]
  }
 ]
}