{
 "title": "Hlášení - dnes",
 "time": { "from": "2024-06-06T00:48:17.101Z", "to": "2024-06-06T12:48:17.103Z" },
 "panels": [
  { "title": "Počasí", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dnešní teplota",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> rename(columns: {_value: \"Maximální teplota\"})\n  |> keep(columns : [\"_time\",\"Maximální teplota\"])\n\n"
    },
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> rename(columns: {_value: \"Průměrná teplota\"})\n  |> keep(columns : [\"_time\",\"Průměrná teplota\"])\n"
    },
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: min, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> rename(columns: {_value: \"Minimální teplota\"})\n  |> keep(columns : [\"_time\",\"Minimální teplota\"])\n"
    }
   ]
  },
  {
   "title": "Průměrná denní teplota za posledních 7 dní",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> mean()\n  |> rename(columns: {_value: \"Maximální teplota\"})\n  |> keep(columns : [\"_time\",\"Maximální teplota\"])\n\n"
    },
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> mean()\n  |> rename(columns: {_value: \"Průměrná teplota\"})\n  |> keep(columns : [\"_time\",\"Průměrná teplota\"])\n"
    },
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: min, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> mean()\n  |> rename(columns: {_value: \"Minimální teplota\"})\n  |> keep(columns : [\"_time\",\"Minimální teplota\"])\n"
    }
   ]
  },
  { "title": "Elektřina", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Dnešní spotřeba elektřiny",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Měřič.*/ and r[\"_measurement\"] != \"Měřič Grid\" and r[\"_measurement\"] != \"Měřič FVE\" and r[\"_measurement\"] != \"Měřič Dům\" and r[\"_measurement\"] != \"Měřič baterie\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  \n"
    },
    {
     "query": "import \"timezone\"\nimport \"regexp\"\nimport \"join\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nspotrebice = from(bucket: \"Kalužovi\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Měřič.*/ and r[\"_measurement\"] != \"Měřič Grid\" and r[\"_measurement\"] != \"Měřič FVE\" and r[\"_measurement\"] != \"Měřič Dům\" and r[\"_measurement\"] != \"Měřič výbíjení baterie\" and r[\"_measurement\"] != \"Měřič nabíjení baterie\" and r[\"_measurement\"] != \"Měřič baterie\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum()\n\nostatni = from(bucket: \"Kalužovi\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Měřič Dům\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n\n//spotrebice\njoin.time(method: \"left\", left: spotrebice, right: ostatni, as: (l, r) => ({l with _value: r._value - l._value}))\n  |> group()"
    }
   ]
  },
  {
   "title": "Průměrná denní spotřeba za posledních 7 dní",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Měřič.*/ and r[\"_measurement\"] != \"Měřič Grid\" and r[\"_measurement\"] != \"Měřič FVE\" and r[\"_measurement\"] != \"Měřič Dům\" and r[\"_measurement\"] != \"Měřič baterie\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> mean()\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  \n"
    },
    {
     "query": "import \"timezone\"\nimport \"regexp\"\nimport \"join\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nspotrebice = from(bucket: \"Kalužovi\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Měřič.*/ and r[\"_measurement\"] != \"Měřič Grid\" and r[\"_measurement\"] != \"Měřič FVE\" and r[\"_measurement\"] != \"Měřič Dům\" and r[\"_measurement\"] != \"Měřič výbíjení baterie\" and r[\"_measurement\"] != \"Měřič nabíjení baterie\" and r[\"_measurement\"] != \"Měřič baterie\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n  |> sum()\n\nostatni = from(bucket: \"Kalužovi\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Měřič Dům\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> group(columns: [\"_time\"], mode:\"by\")\n\n//spotrebice\njoin.time(method: \"left\", left: spotrebice, right: ostatni, as: (l, r) => ({l with _value: r._value - l._value}))\n  |> group()"
    }
   ]
  },
  {
   "title": "Dnešní zdroje elektřiny",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Měřič FVE\" or r[\"_measurement\"] == \"Měřič Grid\" or r[\"_measurement\"] == \"Měřič baterie\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  "
    }
   ]
  },
  {
   "title": "Průměr denních zdrojů za posledních 7 dnů.",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Měřič FVE\" or r[\"_measurement\"] == \"Měřič Grid\" or r[\"_measurement\"] == \"Měřič baterie\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: spread, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> mean()\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  "
    }
   ]
  }
 ]
}