{
 "title": "Počasí",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Teplota",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Kalužovi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(column: \"_value\", usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "Denní průměrná teplota",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> rename(columns: {_value: \"Průměrná teplota\"})\n  |> keep(columns : [\"_time\",\"Průměrná teplota\"])\n"
    },
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> rename(columns: {_value: \"Maximální teplota\"})\n  |> keep(columns : [\"_time\",\"Maximální teplota\"])\n\n"
    },
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Teplota venku\" and r._value != 0)\n  |> aggregateWindow(every: 1d, fn: min, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> rename(columns: {_value: \"Minimální teplota\"})\n  |> keep(columns : [\"_time\",\"Minimální teplota\"])\n"
    }
   ]
  },
  {
   "title": "Srážky",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    {
     "query": "from(bucket: \"Kalužovi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Srážky za den\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(column: \"_value\", usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "Srážky za den",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"Europe/Prague\")\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Srážky za den\")\n  |> aggregateWindow(every: 1d, offset: 3m, fn: max, createEmpty: false, timeSrc: \"_start\")\n  |> fill(column: \"_value\", usePrevious: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n  "
    }
   ]
  },
  {
   "title": "Rychlost větru",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "import \"regexp\"\n\nfrom(bucket: \"Kalužovi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Rychlost větru\" or r[\"_measurement\"] == \"Nárazy větru\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._measurement }))\n"
    }
   ]
  },
  {
   "title": "Směr větru",
   "type": "timeseries",
   "description": "90 - Východní vítr\n180 - Jižní vítr\n270 - Západní vítr\n360 - Severní vítr",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"Kalužovi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Směr větru\" and r._value != 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(column: \"_value\", usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "Sluneční svit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "W/m2" } },
   "targets": [
    {
     "query": "from(bucket: \"Kalužovi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sluneční svit\" and r._value != 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> fill(column: \"_value\", usePrevious: true)\n"
    }
   ]
  }
 ]
}